### ISSUE TITLE
User is not found when searching by username when student has a first/last name

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#110]
## Issue summary
Find by username when student has a first/last name

**Comment by juddus** [comment]
Pretty sure it works.
Just need to show the username underneath the name in results.
I added username under everything apart from the search part I believe due to forgetting.
I'll add that in soon.

#98 is a problem when searching for the exact username usually

**Comment by felixangell** [comment]
Yeah this should work since there is two searches for usernames, first name/last name. I tested this too and it seems fine. Not sure when this was initially filed on the mantis
