### ISSUE TITLE
Empty graphs

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#126]
## Issue summary
Some graphs are empty and not showing any data.

Instead of showing these empty graphs, a message should instead be shown stating there is no data

**Comment by felixangell** [comment]
I noticed this the other day, I made the qa box thing I added show a message... but I thought maybe it'd be better to just not append the entire widget/component/graph? Otherwise you get some pretty large (basically) empty boxes crowding the UI
