### ISSUE TITLE
library search improvements

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#13]
#### Issue
Currently search uses a library called list.js to search through the glps currently loaded onto the page. It does this by searching through the HTML.

Many people have already complained that it doesn't find the GLP they want or that it shows a less relevant result first (mainly due to fuzziness).

Also, once pagination is implemented, entering something in the search will only search a small number of GLPs.

#### TODO
- Remove list.js in favour of search from API
- Try to achieve the same result as the current implementation (results load as you type)

**Comment by juddus** [comment]
#138
