### ISSUE TITLE
Avatars are not working

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#193]
## Issue summary
The same sha256 hash is returned for every avatar, making every avatar identical.

Seems to be happening for `/api/v1/students` and `/api/v1/profile`

**Comment by felixangell** [comment]
the avatar would be cached under the key 'avatar' so the ID was not stored, and thus the last thing to be in the cache would be what is shown/retrieved whenever the avatars are fetched. this is now fixed in the most recent commit

**Comment by juddus** [comment]
For me, this is still happening for the profile avatar.
