### ISSUE TITLE
duplicate active plans

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#20]
#### Issue
Active plans has duplicates. Not sure how to reproduce this currently.

[https://screenshotscdn.firefoxusercontent.com/images/19b63b8c-5551-4a9a-ad9e-fc2135dd2cd2.png](https://screenshotscdn.firefoxusercontent.com/images/19b63b8c-5551-4a9a-ad9e-fc2135dd2cd2.png)

**Comment by juddus** [comment]
Not sure if this is still an issue, needs testing
