### ISSUE TITLE
Custom login interface

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#232]
## Issue summary
Looking ahead to the addition of the parent interface, we should run out own login page to handle login requests.

The login page would need to be accessible, browsable by tabs and keyboard shortcuts and have accessabar. 

It should also include a consent form to accept privacy policy etc.
## Technical details
It might be good to have a separate auth server to handle requests, or run everything inside a docker using traefik to handle load and requests.

**Comment by felixangell** [comment]
Moved to Trello in the Idea section
