### ISSUE TITLE
owned search flag does not work

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#24]
## Issue
Sorting by "owned" still shows plans not owned by the current user. The ownedByMe flag on GLPs is not checked properly it seems.

**Comment by felixangell** [comment]
@juddus this sort will sort by owned by converting the booleans to numbers, so the sorted array would be 1, 1, 1, 1, 0, 0, 0, 0 for example.

But from this I suppose the behaviour should be to only show the ones where owned "true"?

**Comment by juddus** [comment]
I agree it's more of a filter.
Can have a re-jiggle later to organise it more.
