### ISSUE TITLE
Calender 'next' button not working in firefox

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#71]
## Issue summary
The 'next' button to go to the next month works in chrome, but not in Firefox.

## Technical details
Date logic appears to work differently cross browser. 
Getting the first day in chrome has different results to firefox.

**Comment by felixangell** [comment]
Looks like date is implementation dependant :( Firefox uses Z and chrome looks like it uses the users time zone? (so gmt)

I'm going to try a little patch fix but i feel like I might have to port it to use the moment js library (which it looks like we already depend on so no extra dependencies)
