### ISSUE TITLE
students can login to the teacher ui

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#75]
## Issue summary
This is an interesting one. If you login with student details to the UI it will let you do so... though features don't really work.

When you login we do receive a 400 bad request but I guess we dont act upon it. Perhaps another thing we could do after checking the response is maybe ensure that roles contains `teacher` in the profile request?

cc @juddus

**Comment by juddus** [comment]
Yes.
We should check the `roles` contains `teacher`. 
And as said, we shouldn't honour a 400 response status from the API.

**Comment by juddus** [comment]
We should also make our own login page
