### ISSUE TITLE
make calendar search per group or per student

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#83]
## Issue summary
this is from a mantis issue.

they think that we should be consistent and have the sub menu in the classroom page in the calendar. i think this would actually work and be more consistent but the current student selection, i think, is a bit more practical and quicker to use.

i might play around and see how well this works

but cc thoughts 
@HandsFreeComputing

**Comment by juddus** [comment]
This commit made the calendar unusable now.

Currently, this is just stealing the sub navigation bar for classroom, and doesn't work. I left a comment in the code on the commit with more info.

Clicking on the `groups` button should show a dropdown of groups to show in the calendar.
Clicking `students` should show a dropdown of students to display in the calendar

**Comment by felixangell** [comment]
This is the tradeoff of this design is that the calendar would be removed from the main menu and it basically becomes a feature in the classroom.

I kind of like it in terms of consistency. But if it were to be a standalone page it would have to be reverted to the previous system?

If i get your suggestion correctly, where rather than a redirect it would change the current calendar page? That is also nice I might give that a go

**Comment by juddus** [comment]
I think when we fully redesign the interface, that would give us the chance to remove the calendar from the main nav bar. Currently, if we did it, people would think it's a missing feature.

The `students` and `groups` buttons on the second nav bar for calendar should toggle the view, not redirect. This could be done with `this.emit`

**Comment by felixangell** [comment]
This is now implemented with the most recent committ @d77aadb4e62eb04fcbe20823a0b9fe229ed14b28

**Comment by felixangell** [comment]
Implemented as of d77aadb4e62eb04fcbe20823a0b9fe229ed14b28
