### ISSUE TITLE
Make sure GLP names are unique.

### ISSUE THREAD

**Issue by felixangell** [HandsFree/beaconing-teacher-ui#87]
## Issue summary
GLPs can be created with the same name. This is confusing

> GLPs with duplicate name is possible to create. Which ends up in confusion and multiple teachers having access to every GLP created they might choose one GLP to work with because of the duplicacy in names. We actually faced this situation while testing. Two of our testers took the same name for the GLP and was editing in one. Saving the GLP would change the entries and games.

**Comment by felixangell** [comment]
cc @juddus This could technically be Core API peoples problem then we just handle an error request?

**Comment by juddus** [comment]
The issue with this one is that GLPs are shared between teacher accounts.

If a teacher makes a plan named A, should we stop another teacher making a plan named A too?

Many teachers will make GLPs surrounding similar topics. 

Lets say we have 50 teachers using beaconing, and they wanted to make a GLP about algebraic skills. A teacher might make a plan called 'Algebra', another one might try to make one with the same name, see that they can't and make 'Algebra 1', then another makes 'Algebra1', another 'Algebra 2'...

The list of GLPs could become a mess of weird naming conventions, and could become confusing to teachers.

I think a better idea might be to make names unique only for the teacher themselves.
If they make a plan with the same name as a plan made by another teacher, it should suggest looking at that plan before making one with the same name.

cc @HandsFreeComputing

**Comment by felixangell** [comment]
Hmm so a few thoughts:

* Glps are filtered with ones they have created ranked higher than other glps
* When creating a glp similar glps are suggested?
* Perhaps we could show some kind of number that would identify the GLP, e.g.

Teacher John Pickle, jpickle321 creates a GLP:

Algebra
JP-9123894

The JP-{GLP_CODE} is some kind of username displayed under the GLP which would help distinguish their own GLPs?

Or even then with the weighting thing, we could have glps that are created by the teacher highlighted with a border or a star or some kind of thicker accentuating thing?

This is a tricky problem imo

**Comment by juddus** [comment]
I like the idea of having a visual reminder of what are your own GLPs. A thicker border or star are good ideas.

GLPs already display their owner, so a custom ID tag wouldn't have to be made.

"When creating a glp similar glps are suggested?"
This is mainly the point I was wanting to make. Similar GLPs should be suggested to the teacher.

**Comment by felixangell** [comment]
@juddus Aye, was just emphasising that as a question since it wasn't too clear

But yeah sounds cool

**Comment by felixangell** [comment]
Closing this, there are now issues #119 and #120
