### ISSUE TITLE
Search results for a students can appear twice

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#98]
## Issue summary
Searching for a student name can sometimes make the student appear twice

![screenshot_2018-07-04 search](https://user-images.githubusercontent.com/10170940/42288163-82f18a72-7fb1-11e8-93a8-8f2e07e9286a.png)

## Technical Details
JSON returned from backend
```js
{
  "MatchedStudents": [
    {
      "id": 253,
      "username": "johnjones",
      // ...
    },
    {
      "id": 253,
      "username": "johnjones",
      // ...
    },
    {
      "id": 345,
      "username": "newstudenthfctest2",
      // ...
    }
  ],
  "MatchedGLPS": []
}
```

**Comment by felixangell** [comment]
Just realised what the issue is for this, will fix
